"""Manifest-driven composition — auto-generate umbrella re-exports from a manifest.

Inspired by Remix's ``scripts/generate-remix.ts`` which auto-generates
re-exports from a manifest.json, enabling single-package distribution while
maintaining modularity. Applied to aiZee's ``runtime/__init__.py``.

Reads ``manifest.json`` (or a default) describing which modules to re-export,
then regenerates the ``__init__.py`` import block + ``__all__`` list.
"""
from __future__ import annotations

import argparse
import json
import re
import sys
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any


@dataclass
class ManifestEntry:
    """A single re-export entry in the manifest."""

    module: str
    symbol: str
    alias: str | None = None

    @property
    def import_line(self) -> str:
        """Generate the Python import line for this entry."""
        alias_part = f" as {self.alias}" if self.alias else ""
        return f"from {self.module} import {self.symbol}{alias_part}"

    @property
    def export_name(self) -> str:
        """The name exported in __all__."""
        return self.alias or self.symbol


@dataclass
class Manifest:
    """A composition manifest of re-export entries."""

    entries: list[ManifestEntry] = field(default_factory=list)

    def add(self, module: str, symbol: str, alias: str | None = None) -> Manifest:
        """Add an entry. Returns self for chaining."""
        self.entries.append(ManifestEntry(module=module, symbol=symbol, alias=alias))
        return self

    @property
    def export_names(self) -> list[str]:
        """Sorted unique list of exported names for __all__."""
        seen: set[str] = set()
        names: list[str] = []
        for entry in self.entries:
            name = entry.export_name
            if name not in seen:
                seen.add(name)
                names.append(name)
        return sorted(names)

    def to_dict(self) -> dict[str, Any]:
        """Serialize manifest to a dict for JSON storage."""
        return {
            "entries": [
                {"module": e.module, "symbol": e.symbol, "alias": e.alias}
                for e in self.entries
            ]
        }

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> Manifest:
        """Deserialize a manifest from a dict."""
        entries = [
            ManifestEntry(
                module=e["module"],
                symbol=e["symbol"],
                alias=e.get("alias"),
            )
            for e in data.get("entries", [])
        ]
        return cls(entries=entries)


def generate_init_source(
    manifest: Manifest,
    *,
    header: str = "# Auto-generated by scripts/generate_manifest.py — do not edit manually.",
    version_module: str | None = "config",
) -> str:
    """Generate the full __init__.py source from a manifest."""
    lines: list[str] = [header, "", "from __future__ import annotations", ""]
    if version_module:
        lines.append(f"import {version_module}")
        lines.append("")
        lines.append(f"__version__ = {version_module}.VERSION")
        lines.append("")
    lines.append("# Re-export governance modules for convenient access.")
    for entry in manifest.entries:
        lines.append(entry.import_line)
    lines.append("")
    lines.append("__all__ = [")
    for name in manifest.export_names:
        lines.append(f'    "{name}",')
    lines.append("]")
    lines.append("")
    return "\n".join(lines)


def parse_existing_init(source: str) -> Manifest:
    """Parse an existing __init__.py to extract its re-export manifest."""
    manifest = Manifest()
    pattern = re.compile(
        r"^from\s+(\S+)\s+import\s+(\w+)(?:\s+as\s+(\w+))?\s*$"
    )
    for line in source.splitlines():
        match = pattern.match(line.strip())
        if match:
            module, symbol, alias = match.groups()
            if module == "config":
                continue  # skip version import
            manifest.add(module, symbol, alias)
    return manifest


def write_manifest_json(manifest: Manifest, path: Path) -> None:
    """Write the manifest to a JSON file."""
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(
        json.dumps(manifest.to_dict(), indent=2, sort_keys=True),
        encoding="utf-8",
    )


def load_manifest_json(path: Path) -> Manifest:
    """Load a manifest from a JSON file."""
    data = json.loads(path.read_text(encoding="utf-8"))
    return Manifest.from_dict(data)


def main(argv: list[str] | None = None) -> int:
    """CLI entry point: generate or verify __init__.py from manifest."""
    parser = argparse.ArgumentParser(description="Generate runtime/__init__.py from manifest")
    parser.add_argument(
        "--manifest",
        type=Path,
        default=None,
        help="Path to manifest.json (default: derive from existing __init__.py)",
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=None,
        help="Output path (default: print to stdout)",
    )
    parser.add_argument(
        "--verify",
        action="store_true",
        help="Verify existing __init__.py matches manifest (exit 1 if drift)",
    )
    args = parser.parse_args(argv)

    root = Path(__file__).resolve().parent.parent
    init_path = root / "runtime" / "__init__.py"

    if args.manifest and args.manifest.exists():
        manifest = load_manifest_json(args.manifest)
    else:
        existing = init_path.read_text(encoding="utf-8") if init_path.exists() else ""
        manifest = parse_existing_init(existing)

    generated = generate_init_source(manifest)

    if args.verify:
        existing = init_path.read_text(encoding="utf-8") if init_path.exists() else ""
        if existing.strip() != generated.strip():
            print("manifest: drift detected — runtime/__init__.py does not match manifest")
            return 1
        print("manifest: no drift — runtime/__init__.py matches manifest")
        return 0

    if args.output:
        args.output.write_text(generated, encoding="utf-8")
        print(f"manifest: wrote {args.output}")
    else:
        print(generated)
    return 0


if __name__ == "__main__":
    sys.exit(main())
